version: '3.8'
services:
  jenkins_master:
    container_name: jenkins_master
    restart: always
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ../jenkins/master/jenkins-home:/var/jenkins_home
